### ISSUE TITLE
Specifying the orientation and size of gene labels in plotCNlogRByChr

### ISSUE THREAD

**Issue by tinyheero** [gavinha/TitanCNA#1]
Hi Gavin,

I was wondering whether it was possible to specify the size and orientation of the gene labels in the plotCNlogRByChr() function. I am using the geneAnnot parameter to pass in gene labels. It appears the code calls plotGeneAnnotation, and the values seem to be hardcoded.

Thanks,

**Comment by gavinha** [comment]
Hi Fong,

You're right.  At the moment, it is hard-coded.  You will have to pull out the <code>plotGeneAnnotation</code> function and modify it yourself. 
Alternatively, you can save the png or pdf with smaller resolution so that the text is larger, relative to the data points.

I can add this feature in for the next release.  

Best,
Gavin
