### ISSUE TITLE
Clarify the term "cellular prevalence" in the docs

### ISSUE THREAD

**Issue by lbeltrame** [gavinha/TitanCNA#11]
If it is explained in the paper, feel free to close this issue. The definition is clear when you have a single clonal cluster, but when there are more, it gets a little counter-intuitive:

1. If a segment for a specific cluster (say, 4) is listed as a 50% prevalence, does that mean that 50% of the cells of *cluster 4* carry the alteration, or is it referring to the total of the tumor cells?
2. Likewise, `selectSolution` indicates the cellular prevalence in a syntethic way, in order of larger -> smaller (example: 1, 0.86, 0.68). In this case, what does the prevalence signify? The percentage of general alterations in the specific tumor cluster?

**Comment by gavinha** [comment]
Hi Luca,

The cellular prevalence can be defined from 2 perspectives: sample and tumor
1) Sample cellular prevalence = proportion of cells _out of the entire sample_ that contains the event.
2) Tumor cellular prevalence = proportion of cells _out of all the tumor cells_ that contains the event.

In the paper, we refer to the _tumor_ cellular prevalence as simply the cellular prevalence throughout. Likewise, in the parameter files, the cellular prevalence refers to the tumor cellular prevalence. 

> 1. If a segment for a specific cluster (say, 4) is listed as a 50% prevalence, does that mean that 50% of the cells of cluster 4 carry the alteration, or is it referring to the total of the tumor cells?

The 50% prevalence means that events belonging to cluster 4 are found in 50% of cells out of all tumor cells.  All events in cluster 4 will have the same cellular prevalence.

> Likewise, selectSolution indicates the cellular prevalence in a syntethic way, in order of larger -> smaller (example: 1, 0.86, 0.68). In this case, what does the prevalence signify? The percentage of general alterations in the specific tumor cluster?

The tumor cellular prevalence is assigned to each cluster.  In this example, clust1 (1.0), clust2 (0.86), clust3 (0.68).  Note that clust1 is always 1.0 because it refers to the "clonally dominant" cluster such that the event is present in all tumor cells.

For clust2 (0.86), 86% out of tumor cells contain the event (tumor cellular prevalence, `(1-s)` in the paper).  
Let normal contamination be, say, 75%, then the events in clust2 are present in 75%*86%=64.5% of cells out of all cells in the sample including non-tumor cells (sample cellular prevalence, `(1-n)*(1-s)` in the paper).  

Hope this helps.
Best,
Gavin
