### ISSUE TITLE
TitanCNA snakemake pipeline errors

### ISSUE THREAD

**Issue by rhastings** [gavinha/TitanCNA#18]
Hi, 

I'm currently trying to get the snakemake pipeline up and running, I got to the point where the piepline is attempting to run the rule runTitanCNA:

```
rule runTitanCNA:
    input: results/titan/tumCounts/tumor_sample_1.tumCounts.txt, results/ichorCNA/tumor_sample_1/tumor_sample_1.correctedDepth.txt
    output: results/titan/hmm/titanCNA_ploidy3/tumor_sample_1_cluster2.params.txt, results/titan/hmm/titanCNA_ploidy3/tumor_sample_1_cluster2.titan.txt, results/titan/hmm/titanCNA_ploidy3/tumor_sample_1_cluster2/, results/titan/hmm/titanCNA_ploidy3/tumor_sample_1_cluster2.segs.txt, results/titan/hmm/titanCNA_ploidy3/tumor_sample_1_cluster2.seg
    log: logs/titan/hmm/titanCNA_ploidy3/tumor_sample_1_cluster2.log
    jobid: 4
    wildcards: clustNum=2, tumor=tumor_sample_1, ploidy=3
```

The error I get is:
```
In storage.mode(peek.optstring) = spec[current.flag, col.mode] :
  NAs introduced by coercion
Running TITAN...
titan: Loading data results/titan/tumCounts/tumor_sample_1.tumCounts.txt
titan: Loading GC content and mappability corrected log2 ratios...
titan: Extracting read depth...
Removed 46 centromeric positions
Removed Chrs:
titan: Loading default parameters
Model selection: Using 1 cores.
Error in uniroot(funcP, intervalPhi, tol = 1e-15) :
  f.lower = f(lower) is NA
Calls: runEMclonalCN ... estimateClonalCNParamsMap -> updateParameters -> uniroot
Execution halted
```

I've noticed there are some NAs in the file results/ichorCNA/tumor_sample_1/tumor_sample_1.correctedDepth.txt. see below. Could this be the problem? 

```
chr	start	end	log2_TNratio_corrected
1	1000001	2000000	NA
1	2000001	3000000	NA
1	4000001	5000000	-0.115543015089316
1	5000001	6000000	-0.0223702614590051
1	6000001	7000000	-0.106587597655531
1	7000001	8000000	0.0909244472332157
1	8000001	9000000	0.141146096230084
1	9000001	10000000	-0.0804800930951752
```
Any ideas on what's going wrong? 
Thanks
Rob

**Comment by gavinha** [comment]
Hi Rob,

Sorry for the late response.
Typically, the NAs in that file should not be an issue, unless it includes an entire chromosome or leaves very few data points for a particular chromosome. One way to check if it is related to problems with the input data is to try running with different restarts of cluster number and/or ploidy.  For example, use ploidy2 and cluster01 (instead of ploidy3 and cluster02). If it completes successfully, then it is not related to problems in input data. 
I usually only see that error when the sample is either too noisy and the data variance are beyond the expected distributions in the model. Alternatively, for your case here, the data just does not fit the model of ploidy3 and cluster02.

Hope this helps.
Best,
Gavin

**Comment by rhastings** [comment]
Hi Gavin, 

Thanks for the response. After some digging about I noticed that within the config yaml file within the Titan CNA section the `TitanCNA_alphaK` param was set to NULL. I changed this to the default for exome sequencing of 2500 and all seemed to work fine from this point onward. The copy number profiles that come out of TitanCNA are comparable to other programs so I guess it's working ok.
