### ISSUE TITLE
could not find function "extractAlleleReadCounts"

### ISSUE THREAD

**Issue by mnutsua** [gavinha/TitanCNA#20]
Dear Gavin,

I am trying to run TitanCNA with WGS data generated from a matched tumor/normal pair. After preparing the data and reference using the _HHMcopy suite_ according to the vignette on Bioconductor, I tried to run the function "extractAlleleReadCounts" to generate the allele counts file but I get the error message 'could not find function "extractAlleleReadCounts"'. Do I have to load additional packages? Or do I have to generate the file outside from R as well? I do find the help page for the function but cannot use the function itself. I have installed the package (TitanCNA_1.16.0) using Bioconductor.

Many thanks in advance
Marcel

**Comment by gavinha** [comment]
Hi Marcel,

Please treat the function `extractAlleleReadCounts` as being deprecated.  That is, I have not been maintaining it since Rsamtools has changed a lot since I implemented 4 years ago.  I recommend that you generate the allele count data outside of R; it is faster to use samtools (or your own tool of choice) than to do it from within R.  The snakemake workflow [https://github.com/gavinha/TitanCNA/tree/master/scripts/snakemake](https://github.com/gavinha/TitanCNA/tree/master/scripts/snakemake), particularly the tasks in [getAlleleCounts.snakefile](https://github.com/gavinha/TitanCNA/blob/master/scripts/snakemake/getAlleleCounts.snakefile) will help you get what you want. 

Hope this helps.

I will task myself to also remove the manual page for this function and remove it from the vignette if it's still there.

Best,
Gavin
