### ISSUE TITLE
Parameter Setting: maxPloidy

### ISSUE THREAD

**Issue by lijinsgithub** [gavinha/TitanCNA#23]
Would you please suggest how to set some parameters?

I am working on 26 samples from 13 ovarian cancer patients but not sure if my choice of parameters was good enough. Currently, I set the maxPloidy at 4 but I found that 9 out of 26 samples were estimated to have Ploidy at 4. Do I need to increase the max Ploidy greater?

To break my questions down further,
1. Do I need to change max Ploidy higher?
2. How Ploidy and N of Cluster are related in your algorithm? 
    Would you mind to point a place, which section/page of a paper, if you already described in your publication?
3. Are there any other parameters need to be updated?
4. About model anomalies.
  I have three samples, whose purity is less than 0.3.
  Also, I got two samples converge to log-lik = - Inf.
 
  What are your suggestions on these anomalies? Do I need to dump them?

Lastly, I am using "snakemake" as you suggested before  and it's fantastic!
Thank you again your answers in advance (please!) and also for developing and maintaining this wonderful application with us!

Bests,
Lijin

**Comment by gavinha** [comment]
Hi @lijinsgithub 

Sorry for the delay in responding.

1. Do I need to change max Ploidy higher?

I do not think you need to increase the ploidy. 

2. How Ploidy and N of Cluster are related in your algorithm?
Would you mind to point a place, which section/page of a paper, if you already described in your publication?

Ploidy is an unknown parameter that is estimated each time TitanCNA is run (ie for each solution). We recommend that you use different initializations (restarts) so that it may have more chances to arrive at an optimal solution.  Number of clusters is not estimated but simply set and fixed. We generally iterate over a maximum number of clusters for a given solution so that we can arrive at an optimal solution.  For example, TitanCNA is run for 1 total number of clusters considered (i.e. cluster01 solution), then run for 2 total number of clusters considered (i.e. cluster01). Note that even though 2 clusters is considered, the results may return with 1 or 2 clusters in the solution.  I hope this makes sense.  
This is mentioned somewhat in the methods of the paper when describing how the optimal solution is selected.

3. Are there any other parameters need to be updated?
If you are observing too many segments (i.e. over-segmentation) you can set the transition matrix probabilities:
https://github.com/gavinha/TitanCNA/blob/1b0d954293435c0fdd51fce769eba01b3164928c/scripts/R_scripts/titanCNA.R#L61-L62

4. About model anomalies.
I have three samples, whose purity is less than 0.3.
Do the plots support this result? Is this unexpected?

Also, I got two samples converge to log-lik = - Inf.
This usually results when there are no copy number events (detectable).

Hope this helps.

Best,
Gavin

**Comment by lijinsgithub** [comment]
Thank you very much for kind and helpful responses all the time!
