### ISSUE TITLE
Error in runEMclonalCN with low coverage bam files

### ISSUE THREAD

**Issue by evanbiederstedt** [gavinha/TitanCNA#4]
Thanks for releasing this great software!
I've been running TitanCNA on bams with coverage 1x, 5x, 10x, and 20x. 

There's consistently an error for the low coverage bam files of 1-5x coverage. As an example, here is the output I'm seeing for the low coverage bam files:

```
Running TITAN...
titan: Loading data input.hets.txt
titan: Loading GC content and mappability corrected log2 ratios...
titan: Extracting read depth...
Removed 0 centromeric positions
titan: Loading default parameters
Loading required package: iterators
Using 4 cores.
titan: Running HMM...
fwdBack: Iteration 1 chr: 1 2 Error in { : 
  task 1 failed - "INTEGER() can only be applied to a 'integer', not a 'NULL'"
Calls: runEMclonalCN -> %dopar% -> <Anonymous>
Execution halted
```

TITAN works perfectly for the 20x and 40x coverage files though:

```
Running TITAN...
titan: Loading data input.hets.txt
titan: Loading GC content and mappability corrected log2 ratios...
titan: Extracting read depth...
Removed 0 centromeric positions
titan: Loading default parameters
Loading required package: iterators
Using 4 cores.
titan: Running HMM...
fwdBack: Iteration 1 chr: 1 2 3 4 8 7 6 5 12 11 9 10 16 15 13 14 20 19 23 18 17 21 22 
Coord Descent[1]=-561231 n=0.5 s=[0.001,0.200,0.300] phi=4
Coord Descent[2]=-274262 n=0.2084 s=[0.051,0.204,0.344] phi=4.016
Coord Descent[3]=-272542 n=0.2943 s=[0.05,0.20,0.34] phi=4.014
Coord Descent[4]=-272522 n=0.2948 s=[0.052,0.196,0.341] phi=4.014
Coord Descent[5]=-272522 n=0.2946 s=[0.052,0.196,0.341] phi=4.014
...
```

Is it possible that `runEMclonalCN` is getting stuck at gaps in the coverage? Have you noticed there's a "minimal coverage" necessary for TITAN to work properly?

**Comment by gavinha** [comment]
Hi,

This is expected as TitanCNA was designed for higher coverage WGS data.  The main reason is that heterozygous SNP sites need to be covered with a minimum depth in order to properly estimate allelic imbalance.

When you invoked the function `filterData()`, there is an argument for `minDepth`.  By default, this is set to 10.  What has happened is that some chromosomes have been filtered such that there are too few data points or none at all.   

I have developed a new copy number tool that looks at total copy number from coverages as low as 0.1x coverage.  This tool, called ***ichorCNA***, will be released soon (next few days or weeks).  ichorCNA builds on top of HMMcopy and is optimized for low coverages (as well as high).  While it will handle subclonal copy number, estimate tumor content and ploidy, it will not produce allelic copy number.  Not sure if this will be useful for you.

Hope this helps.
Best,
Gavin

**Comment by evanbiederstedt** [comment]
Hi Gavin

Thanks for the quick response!

Just to be clear: is there any parameter I could set to run TITAN on 1x or 5x coverage bams? Or is it correct to conclude that TITAN cannot run on bams with such low coverage? 

Thanks, Evan

**Comment by gavinha** [comment]
Hi Evan,

At the moment, TITAN would not produce reliable allelic copy number at 5x or lower coverage. If you want it to run to completion, then you can adjust the `minDepth` argument so that `filterData()` doesn't remove nearly all your data points. 

If you have haplotype phasing of SNPs from the normal, then TITAN might be able to generate large-scale haplotype-based CN.  Although I've never tested it on 5x data.  This version is being developed in an alternative branch.

If you only want total copy number, then HMMcoy (and soon, ichorCNA), among other coverage-only-based segmentation algorithms such as Control-FreeC, BICseq, etc. should work.

Best,
Gavin

**Comment by evanbiederstedt** [comment]
I understand. Thanks for the help. I will try with `minDepth=1`, solely to see whether the algorithm runs. However, I will wait for your new package for a reliable approach.

**Comment by gavinha** [comment]
Hi Evan,

ichorCNA is publicly available now
https://github.com/broadinstitute/ichorCNA

Please take a look to see if this tool is suitable for your analysis.

Best,
Gavin
