### ISSUE TITLE
Warn when data is different from the genome style

### ISSUE THREAD

**Issue by lbeltrame** [gavinha/TitanCNA#5]
Correcting reads with targeted regions failed because I had `genomeStyle` set to `NCBI` while my data was in `UCSC` style, therefore no overlaps would be found.

**Comment by gavinha** [comment]
Hi Luca,

Can you provide the lines of code that generated the problem?  

Referring to [titanCNA.R](https://github.com/gavinha/TitanCNA/blob/master/scripts/R_scripts/titanCNA.R), I'm guessing the problem lies in these lines of code:

https://github.com/gavinha/TitanCNA/blob/35e317234a22fdb138d59fe2c1b9eac37cf00fee/scripts/R_scripts/titanCNA.R#L150
https://github.com/gavinha/TitanCNA/blob/35e317234a22fdb138d59fe2c1b9eac37cf00fee/scripts/R_scripts/titanCNA.R#L140
https://github.com/gavinha/TitanCNA/blob/35e317234a22fdb138d59fe2c1b9eac37cf00fee/scripts/R_scripts/titanCNA.R#L154

Here, `cnData` is the output of `correctReadcount()`.  Using `setGenomeStyle()`, you can ensure that both `cnData` and `data` use the same naming convention.  

Here's what I can do. 
1. Add a check in `getPositionOverlap()` so that it completely handles any naming mismatches within.
2. Then, build `getPositionOverlap()` directly into `loadAlleleCounts()` such that users will pass in `cnData` as an additional argument to `loadAlleleCounts()` and then it will return `data` with the logR column.  This should save some lines in your R script.

Best,
Gavin

**Comment by lbeltrame** [comment]
It breaks here:

```R

 if (!is.null(targetedSequence)) {
        message("Analyzing targeted regions...")
        targetIR <- RangedData(ranges = IRanges(start = targetedSequence[, 2], 
                    end = targetedSequence[, 3]), space = targetedSequence[, 1])
                    
        #keepInd <- unlist(as.list(findOverlaps(tumour_reads, targetIR, select = "first")))
        #keepInd <- !is.na(keepInd)
        hits <- findOverlaps(query = tumour_reads, subject = targetIR)
        keepInd <- unique(queryHits(hits))    
```

`keepInd` will be a zero-length vector, and thus when applied to the tumor and normal counts will generate empty tables.

**Comment by gavinha** [comment]
Hi Luca,

I understand your question now.  This is because `targetedSequence` uses another chromosome naming convention.  

I will use `setGenomeStyle()` on `targetedSequence[,1]`.
